### ISSUE TITLE
tmtsprite 有问题

### ISSUE THREAD

**Issue by iamike** [TmT/WxMoment#7]
经过我的详细调查，应该是他

**Comment by hzlzh** [comment]
@iamike 遇到什么问题？wxmoment 相关的请到 https://github.com/wxc-team/WxMoment 具体描述并提出。
另外， Gulp 工作流有更新，见：https://github.com/weixin/tmt-workflow

GOTO: https://github.com/weixin/tmt-workflow/issues/15
